ChatBot/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', index),
]

PersonalArea/urls.py
from django.urls import path
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path("", views.other.index),
    path("chat/", views.other.chat),

    path("users/list/", views.administration.users_list),
    path("users/list/<str:role>", views.administration.users_list),
    path("users/create/", views.admin.user_create, name="create_user"),
    path("users/<int:id>/edit/", views.administration.edit_user),
    path("users/<int:id>/delete/", views.admin.user_delete),
    path("users/data/<int:id>", views.administration.user_data),
    path("users/<int:id>/view/", views.administration.view_user),
    path("users/<int:user>/login/", views.admin.login_admin_user),
    path("users/<int:user>/avatar/remove", views.administration.avatar_remove),
    path("events/<int:id>/view/", views.aam.events_view),
    path("events/category/list/", views.admin.category_list, name="category_list"),
    path("events/category/<int:id>/edit/", views.admin.category_edit),
    path("events/<int:id>/accept/<int:user>", views.aam.event_accept_user),
    path("events/<int:id>/reject/<int:user>", views.aam.event_reject_user),
    path("events/<int:id>/add/<int:user>", views.admin.event_add_user),
    path("events/<int:id>/export", views.aam.event_export),
    path("events/<int:id>/unarchived", views.aam.event_unarchived),
    path("events/<int:id>/archive", views.aam.event_archive),
    path("events/<int:id>/points/give", views.aam.give_points),
    path("events/<int:id>/photo/report", views.aam.photo_report),
    path("events/<int:id>/photo/report/<int:image>/delete", views.aam.photo_delete),
    path("events/<int:id>/detail", views.other.event_detail),
    path("events/category/data/<int:id>", views.admin.category_data),
    path("events/invites/", views.student.student_invites),
    path("events/all_events/", views.other.all_events),

    path("building/list/", views.admin.building_list),
    path("building/add/", views.admin.add_building),
    path("events/list/<str:search>", views.aam.events_list),
    path("events/archive/", views.aam.events_archive_list),
    path('settings/', views.other.edit_profile),
    path("events/create/", views.aam.event_create),

    path("classroom/create/", views.teacher.create_classroom),
    path("events/", views.other.events),
    path("events/<int:id>/invite", views.teacher.invite_classroom_event),

    path("classroom/invite/create/", views.teacher.create_invite),
    path("classroom/invite/update/", views.teacher.update_invite),
    path("classroom/invite/<uuid:classroom>/", views.student.invite),
    path("classroom/students/", views.teacher.classroom_students),

    path("classroom/student/<int:user>/view", views.teacher.classroom_view_student),
    path("classroom/student/<int:user>/export", views.other.classroom_view_export),

    path("events/<int:event>/request", views.student.event_request),
    path("my/events/", views.student.my_events),

    path("classrooms/", views.administration.classrooms_list, name="classrooms_list"),
    path("classrooms/<int:id>", views.administration.classrooms_view, name="classrooms_view"),
    path("settings/avatar/remove", views.other.avatar_remove, name="avatar_remove"),
    path('schedule/', views.psychologist.schedule_index, name="schedule_index"),
    path('schedule/add', views.psychologist.schedule_add, name="schedule_add"),

    path('schedule/<int:d>/<int:m>/<int:y>', views.psychologist.schedule_date, name="schedule_date"),
    path('schedule/calendar/', views.psychologist.calendar, name="calendar"),
    path('schedule/edit', views.psychologist.edit_schedule, name="edit_schedule"),
    path('schedule/has_month_classes/<int:m>/<int:y>', views.psychologist.has_month_classes, name="has_month_classes"),
    path('schedule/view/<int:id>', views.psychologist.view_schedule, name="view_schedule"),
    path('classes', views.psychologist.classes, name="classes"),
    path("settings/security/change-password/", views.other.change_password, name="change_password"),
    path("settings/security/devices/", views.other.devices, name="security"),
    path("settings/security/devices/delete/<str:device>", views.other.delete_device, name="delete_device"),
    path("settings/linking/mosru", views.other.settings_linking_mosru, name="settings_linking_mosru"),
# path("classroom/student/<int:user>/delete", views.classroom_delete_student),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

volunteer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from Accounts import views as accounts_views
from MainApp import views
from django.views.static import serve

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('register/<str:mode>/', accounts_views.register),
                  path('login/', accounts_views.login_request),
                  path('logout/', accounts_views.logout_request, name="logout"),

                  path('lk/', include("PersonalArea.urls")),
                  path('setup/', accounts_views.setup, name="setup"),
                  path('', views.index),
                  path('auth/', accounts_views.auth, name="auth"),
                  path('auth/mosru/', accounts_views.auth_mos_ru, name="auth"),
                  path('auth/mosru/info/', accounts_views.mos_ru_info, name="auth"),
                  path('auth/register', accounts_views.register_request),
                  path('auth/login', accounts_views.login_request),
                  path('chatbot/', include("ChatBot.urls")),
                  path("user_activity/", accounts_views.user_activity),
                  path("feedback/", views.feedback)
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


def handler404(request, *args, **argv):
    return render(request, 'errors/404.html', status=404)


def handler500(request, *args, **argv):
    return render(request, 'errors/500.html', status=500)


def handler403(request, *args, **argv):
    return render(request, 'errors/403.html', status=403)


handler403 = handler403
handler500 = handler500
handler404 = handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MainApp/models.py
import random
import time
from datetime import datetime, timedelta

import django.contrib.auth
from django.db import models
from django.core import validators
from django.db.models import Q
from django.db.models.signals import post_delete
from django.dispatch import receiver

Account = "Accounts.account"
from multiselectfield import MultiSelectField
import uuid


class EventsMembers(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    points = models.IntegerField(validators=[
        validators.MinValueValidator(0),
        validators.MaxValueValidator(100)
    ], null=True)
    is_active = models.BooleanField(default=False)


class ClassRoomsNumber(models.Model):
    name = models.CharField(max_length=255)
    value = models.IntegerField()

    def __str__(self):
        return self.name


class EventCategory(models.Model):
    name = models.CharField(max_length=255)
    methodists = models.ManyToManyField(Account, limit_choices_to={"role": "methodist"}, blank=True)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Катигории"

    def __str__(self):
        return self.name


class Subjects(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Предмет"
        verbose_name_plural = "Предметы"

    def __str__(self):
        return self.name


class Events(models.Model):
    CLASSROOM = [
        ("0", "Детский сад"),
        ("1", "1 класс"),
        ("2", "2 класс"),
        ("3", "3 класс"),
        ("4", "4 класс"),
        ("5", "5 класс"),
        ("6", "6 класс"),
        ("7", "7 класс"),
        ("8", "8 класс"),
        ("9", "9 класс"),
        ("10", "10 класс"),
        ("11", "11 класс")
    ]
    TYPES = [
        ("subject", "Предметное"),
        ("methodist", "Методическое")
    ]
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=2550)

    start_date = models.DateTimeField(auto_now=False)
    end_date = models.DateTimeField(auto_now=False)

    classroom_number = models.CharField(max_length=255, choices=CLASSROOM, null=True)
    type = models.CharField(max_length=255, choices=TYPES, null=True, default="subject")

    archive = models.BooleanField(default=False)

    image = models.ImageField(upload_to="images", null=True)

    subject = models.ForeignKey(Subjects, on_delete=models.SET_NULL, null=True, related_name="subject", blank=True)
    category = models.ForeignKey(EventCategory, related_name="category", on_delete=models.SET_NULL, null=True,
                                 blank=True)
    organizer = models.ForeignKey(Account, on_delete=models.SET_NULL, related_name="organizer", null=True)
    building = models.ForeignKey("Accounts.building", on_delete=models.SET_NULL, related_name="building", null=True)

    volunteer = models.ManyToManyField(EventsMembers, related_name="volunteers", blank=True)

    class Meta:
        verbose_name = "Мероприятие"
        verbose_name_plural = "Мероприятия"

    def __str__(self):
        return f"{self.name} - {self.volunteer}"


def f(instance, filename):
    ext = filename.split('.')[-1]
    return '{}.{}'.format(f"photo_reports/{instance.event.pk}/{uuid.uuid4()}", ext)


class PhotoReport(models.Model):
    image = models.ImageField(upload_to=f)
    event = models.ForeignKey(Events, on_delete=models.CASCADE, null=True)
    uploaded = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)
    author = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)


@receiver(post_delete, sender=PhotoReport)
def delete_image_file(sender, instance, **kwargs):
    print("delete_image_file")
    instance.image.delete(False)


class ClassRoom(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    teacher = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="teacher", null=True)
    member = models.ManyToManyField(Account, related_name="students", blank=True)
    classroom = models.IntegerField()
    parallel = models.CharField(max_length=1)

    def invite_url(self):
        return f"https://mysite.com:8000/lk/classroom/invite/{self.uuid}/"

    def __str__(self):
        return f"{self.classroom}\"{self.parallel}\""

    class Meta:
        verbose_name = "Класс"
        verbose_name_plural = "Классы"


class PsychologistSchedule(models.Model):
    psychologist = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="psychologist",
                                     limit_choices_to={"role": "psychologist"})
    child = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="child",
                              limit_choices_to=Q(peculiarity__in=["handicapped", "autism"]))
    date = models.DateField(null=True)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    comment = models.TextField(max_length=2550, null=True, blank=True)

    def __str__(self):
        return f"{self.child} - {self.date}"

    def can_move(self):
        dt = datetime.now()
        if self.date <= dt.date():
            return False
        elif (self.date - dt.date()).days <= 2:
            print((self.date - dt.date()).days)
            return False
        else:
            return True

class TeacherInviteEvent(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="account")
    classroom = models.ForeignKey(ClassRoom, on_delete=models.CASCADE, related_name="event_classroom")
    event = models.ForeignKey(Events, on_delete=models.CASCADE, related_name="event_teacher")

    class Meta:
        verbose_name = "Приглашение на мероприятие"
        verbose_name_plural = "Приглашения на мероприятия"

PersonalArea/views/admin.py
import uuid
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse, FileResponse
from django.shortcuts import render, redirect, get_object_or_404
from Accounts.models import Account
from MainApp.models import *
from django.utils.formats import localize

from PersonalArea.forms import *
from Accounts.forms import NewBuildingForm
from Accounts.models import Building
from Accounts import decorators
import io
import xlsxwriter
import pandas as pd
from PersonalArea.models import Notications, Message


@decorators.is_admin
def login_admin_user(request, user):
    if request.user.is_superuser:
        logout(request)
        user = get_object_or_404(Account, pk=user)
        login(request, user)
        return redirect("/lk/")


@decorators.is_admin
def user_create(request):
    if request.method == "GET":
        return redirect("/lk/users/list")
    else:
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=True)
        return redirect("/lk/users/list")
    return render(request, "adminpanel/user_create.html", {"form": form})

@decorators.is_admin
def user_delete(request, id):
    user = get_object_or_404(Account, pk=id)
    user.delete()
    return redirect("/lk/users/list")
@decorators.is_admin
def event_add_user(request, id, user):
    user = Account.objects.get(id=user)
    user = EventsMembers(user=user, is_active=False)
    user.save()
    event = Events.objects.get(pk=id)
    event.volunteer.add(user)
    return redirect(f"/lk/events/{id}/view")


@decorators.is_admin
def add_building(request):
    if request.method == "GET":
        form = NewBuildingForm()
    else:
        form = NewBuildingForm(request.POST)
        if form.is_valid():
            user = form.save(commit=True)
        return redirect("/lk/building/list")
    return render(request, "adminpanel/building_create.html", {"form": form, "section": "building"})


@decorators.is_admin
def building_list(request):
    context = {
        "buildings": Building.objects.all().order_by("-id"),
        "section": "building"
    }
    return render(request, "adminpanel/buildings_list.html", context=context)


@decorators.is_admin
def category_list(request):
    if request.method == "POST":
        form = EventCategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
    categories = EventCategory.objects.all()
    form = EventCategoryForm()
    return render(request, "adminpanel/category_list.html",
                  {"categories": categories, "form": form, "section": "events"})


@decorators.is_admin
def category_data(request, id):
    category = EventCategory.objects.get(pk=id)
    category_data = {
        'received': localize(datetime.now()),
        'category': {
            "id": category.id,
            "name": category.name,
            "methodists": {}
        }
    }
    for i in category.methodists.all():
        category_data['category']['methodists'][i.pk] = {
            "id": i.pk,
            "full_name": i.full_name(),

        }
    return JsonResponse(category_data, safe=False)


@decorators.is_admin
def category_edit(request, id):
    category = EventCategory.objects.get(pk=id)
    if request.method == "POST":
        form = EventCategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            form.save_m2m()
        return redirect("category_list")
    else:
        form = EventCategoryForm(instance=category)
        return render(request, "adminpanel/edit_category.html", {"section": "events", "form": form})

PersonalArea/views/student.py
import uuid
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, FileResponse
from django.shortcuts import render, redirect, get_object_or_404
from Accounts.models import Account
from MainApp.models import *
from django.utils.formats import localize

from PersonalArea.forms import *
from Accounts.forms import NewBuildingForm
from Accounts.models import Building
from Accounts import decorators
import io
import xlsxwriter
import pandas as pd
from PersonalArea.models import Notications, Message



@decorators.is_student
def invite(request, classroom):
    classroom = ClassRoom.objects.get(uuid=classroom)
    classroom.member.add(request.user)
    classroom.save()
    messages.success(request, "Вы успешно вошли в класс")
    return redirect("/lk/")



@decorators.is_student
def event_request(request, event):
    event = Events.objects.get(pk=event)
    member = EventsMembers(user=request.user)
    member.save()
    event.volunteer.add(member)
    messages.success(request, "Вы успешно подали заявку на мероприятие")
    return redirect("/lk/events/")


@decorators.is_student
def my_events(request):
    events = Events.objects.all().filter(volunteer__user=request.user)
    wait = events.filter(start_date__gt=datetime.now())
    ended = events.filter(end_date__lt=datetime.now())
    started = events.filter(end_date__gt=datetime.now(), start_date__lte=datetime.now())
    return render(request, "student/my_events.html", {"started": started, "ended": ended, "wait": wait, 'section': 'my_events'})

@decorators.is_student
def student_invites(request):
    pass

PersonalArea/templates/adminpanel/building_create.html
{% extends "inc/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Добавление здания</h6>
                <form method="post">
                    <div class="mb-3">
                        {% csrf_token %}
                        {{ form|crispy}}
                    </div>
                    <button type="submit" class="btn btn-primary">Создать</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

PersonalArea/templates/adminpanel/building_view.html
{% extends "inc/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-12 col-xl-12">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">Классы
                    </h6>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Класс</th>
                            <th scope="col">Учитель</th>
                            <th scope="col">Учеников</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for classroom in classrooms %}

                            <tr>
                                <th scope="row"><a href="/classrooms/{{ classroom.id }}">{{ classroom.id }}</a></th>
                                <td>{{ classroom }}</td>
                                <td>{% if classroom.teacher %}{{ classroom.teacher.full_name }}{% else %}Не
                                    зарегистрирован(а){% endif %}</td>
                                <td>{{ classroom.member.count }}</td>
                            </tr>


                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

PersonalArea/templates/adminpanel/buildings_list.html
{% extends "inc/base.html" %}
{% block content %}
<!-- Sales Chart Start -->
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Здания
                </h6>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">Тип</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for building in buildings %}
                        <tr>
                            <td>{{building.name}}</td>
                            <td>{{building.get_type_display}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Sales Chart End -->


{% endblock content %}

PersonalArea/templates/adminpanel/edit_category.html
{% extends "inc/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-light rounded h-100 p-4">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

PersonalArea/templates/adminpanel/index.html
{% extends "inc/base.html" %}
{% block content %}
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-6 col-xl-3">
                <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                    <i class="fa fa-users fa-3x text-primary"></i>
                    <div class="ms-3">
                        <p class="mb-2">Пользователей</p>
                        <h6 class="mb-0">{{ users }}</h6>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xl-3">
                <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                    <i class="fa fa-calendar fa-3x text-primary"></i>
                    <div class="ms-3">
                        <p class="mb-2">Мероприятий</p>
                        <h6 class="mb-0">{{ events }}</h6>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xl-3">
                <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                    <i class="fa fa-user-plus fa-3x text-primary"></i>
                    <div class="ms-3">
                        <p class="mb-2">Заявок</p>
                        <h6 class="mb-0">{{ reqs }}</h6>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xl-3">
                <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                    <i class="fa fa-building fa-3x text-primary"></i>
                    <div class="ms-3">
                        <p class="mb-2">Корпус</p>
                        <h6 class="mb-0">{{ builds }}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Sale & Revenue End -->
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-24 col-xl-12">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">Топ баллов</h6>
                    <canvas id="myChart"></canvas>

                    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

                    <script>
                        const ctx = document.getElementById('myChart');

                        new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels: [{% for student in students %} '{{ student.full_name }}', {% endfor %}],
                                datasets: [{
                                    label: 'баллы',
                                    data: [{% for student in students %} {{ student.points }}, {% endfor %}],
                                    borderWidth: 2,
                                    backgroundColor: [
                                        'rgba(255, 206, 86, 0.8)',
                                        'rgba(255, 99, 132, 0.8)',
                                        'rgba(54, 162, 235, 0.8)',
                                        'rgba(75, 192, 192, 0.8)',
                                        'rgba(153, 102, 255, 0.8)',
                                        'rgba(255, 159, 64, 0.8)',
                                        'rgba(240, 120, 50, 0.8)',
                                    ],
                                    borderColor: [
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)',
                                        'rgba(240, 120, 50, 1)',

                                    ],
                                }]
                            },
                            options: {
                                scales: {
                                    y: {
                                        beginAtZero: true
                                    }
                                }
                            }
                        });
                    </script>


                </div>
            </div>
        </div>
    </div>



{% endblock content %}

PersonalArea/templates/adminpanel/user_create.html
{% extends "inc/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Создание пользователя</h6>
                <form method="post">
                    <div class="mb-3">
                        {% csrf_token %}
                        {{ form|crispy}}
                    </div>
                    <button type="submit" class="btn btn-primary">Создать</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}