ChatBot/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', index),
]

PersonalArea/urls.py
from django.urls import path
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path("", views.other.index),
    path("chat/", views.other.chat),

    path("users/list/", views.administration.users_list),
    path("users/list/<str:role>", views.administration.users_list),
    path("users/create/", views.admin.user_create, name="create_user"),
    path("users/<int:id>/edit/", views.administration.edit_user),
    path("users/<int:id>/delete/", views.admin.user_delete),
    path("users/data/<int:id>", views.administration.user_data),
    path("users/<int:id>/view/", views.administration.view_user),
    path("users/<int:user>/login/", views.admin.login_admin_user),
    path("users/<int:user>/avatar/remove", views.administration.avatar_remove),
    path("events/<int:id>/view/", views.aam.events_view),
    path("events/category/list/", views.admin.category_list, name="category_list"),
    path("events/category/<int:id>/edit/", views.admin.category_edit),
    path("events/<int:id>/accept/<int:user>", views.aam.event_accept_user),
    path("events/<int:id>/reject/<int:user>", views.aam.event_reject_user),
    path("events/<int:id>/add/<int:user>", views.admin.event_add_user),
    path("events/<int:id>/export", views.aam.event_export),
    path("events/<int:id>/unarchived", views.aam.event_unarchived),
    path("events/<int:id>/archive", views.aam.event_archive),
    path("events/<int:id>/points/give", views.aam.give_points),
    path("events/<int:id>/photo/report", views.aam.photo_report),
    path("events/<int:id>/photo/report/<int:image>/delete", views.aam.photo_delete),
    path("events/<int:id>/detail", views.other.event_detail),
    path("events/category/data/<int:id>", views.admin.category_data),
    path("events/invites/", views.student.student_invites),
    path("events/all_events/", views.other.all_events),

    path("building/list/", views.admin.building_list),
    path("building/add/", views.admin.add_building),
    path("events/list/<str:search>", views.aam.events_list),
    path("events/archive/", views.aam.events_archive_list),
    path('settings/', views.other.edit_profile),
    path("events/create/", views.aam.event_create),

    path("classroom/create/", views.teacher.create_classroom),
    path("events/", views.other.events),
    path("events/<int:id>/invite", views.teacher.invite_classroom_event),

    path("classroom/invite/create/", views.teacher.create_invite),
    path("classroom/invite/update/", views.teacher.update_invite),
    path("classroom/invite/<uuid:classroom>/", views.student.invite),
    path("classroom/students/", views.teacher.classroom_students),

    path("classroom/student/<int:user>/view", views.teacher.classroom_view_student),
    path("classroom/student/<int:user>/export", views.other.classroom_view_export),

    path("events/<int:event>/request", views.student.event_request),
    path("my/events/", views.student.my_events),

    path("classrooms/", views.administration.classrooms_list, name="classrooms_list"),
    path("classrooms/<int:id>", views.administration.classrooms_view, name="classrooms_view"),
    path("settings/avatar/remove", views.other.avatar_remove, name="avatar_remove"),
    path('schedule/', views.psychologist.schedule_index, name="schedule_index"),
    path('schedule/add', views.psychologist.schedule_add, name="schedule_add"),

    path('schedule/<int:d>/<int:m>/<int:y>', views.psychologist.schedule_date, name="schedule_date"),
    path('schedule/calendar/', views.psychologist.calendar, name="calendar"),
    path('schedule/edit', views.psychologist.edit_schedule, name="edit_schedule"),
    path('schedule/has_month_classes/<int:m>/<int:y>', views.psychologist.has_month_classes, name="has_month_classes"),
    path('schedule/view/<int:id>', views.psychologist.view_schedule, name="view_schedule"),
    path('classes', views.psychologist.classes, name="classes"),
    path("settings/security/change-password/", views.other.change_password, name="change_password"),
    path("settings/security/devices/", views.other.devices, name="security"),
    path("settings/security/devices/delete/<str:device>", views.other.delete_device, name="delete_device"),
    path("settings/linking/mosru", views.other.settings_linking_mosru, name="settings_linking_mosru"),
# path("classroom/student/<int:user>/delete", views.classroom_delete_student),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

volunteer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from Accounts import views as accounts_views
from MainApp import views
from django.views.static import serve

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('register/<str:mode>/', accounts_views.register),
                  path('login/', accounts_views.login_request),
                  path('logout/', accounts_views.logout_request, name="logout"),

                  path('lk/', include("PersonalArea.urls")),
                  path('setup/', accounts_views.setup, name="setup"),
                  path('', views.index),
                  path('auth/', accounts_views.auth, name="auth"),
                  path('auth/mosru/', accounts_views.auth_mos_ru, name="auth"),
                  path('auth/mosru/info/', accounts_views.mos_ru_info, name="auth"),
                  path('auth/register', accounts_views.register_request),
                  path('auth/login', accounts_views.login_request),
                  path('chatbot/', include("ChatBot.urls")),
                  path("user_activity/", accounts_views.user_activity),
                  path("feedback/", views.feedback)
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


def handler404(request, *args, **argv):
    return render(request, 'errors/404.html', status=404)


def handler500(request, *args, **argv):
    return render(request, 'errors/500.html', status=500)


def handler403(request, *args, **argv):
    return render(request, 'errors/403.html', status=403)


handler403 = handler403
handler500 = handler500
handler404 = handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Accounts/models.py
import random
import time
import uuid

from MainApp.models import EventsMembers, ClassRoom
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, User

class MyAccountManager(BaseUserManager):
    def create_user(self, email=None, second_name=None, first_name=None, middle_name=None, password=None,
                    username: str = None):
        if username is None:
            raise ValueError("User must have an username.")
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            second_name=second_name,
            first_name=first_name,
            middle_name=middle_name
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password, second_name, first_name, middle_name):
        user = self.create_user(email=self.normalize_email(email),
                                username=username,
                                password=password,
                                second_name=second_name,
                                first_name=first_name,
                                middle_name=middle_name
                                )
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class Building(models.Model):
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255, choices=[("school", "Школа"), ('kg', 'Детский сад')], blank=True)

    def __str__(self):
        return self.name


def f(instance, filename):
    ext = filename.split('.')[-1]
    return '{}.{}'.format(f"avatars/{instance.pk}/{uuid.uuid4()}", ext)


class Account(AbstractBaseUser):
    ROLES = [
        ("admin", "Администратор"),
        ("teacher", "Учитель"),
        ("parent", "Родитель"),
        ("student", "Ученик"),
        ("methodist", "Методист"),
        ("director", "Директор"),
        ("head_teacher", "Завуч"),
        ("psychologist", "Психолог"),
    ]
    PECULARITY_CHOICE = [
        ("handicapped", "Инвалидность"),
        ("autism","Аутизм")
    ]
    TWO_AUTH_CHOICES = [
        ("email", "email"),
    ]
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    role = models.TextField(choices=ROLES, null=True, max_length=20)
    first_name = models.CharField(max_length=50, null=True)  # Имя
    second_name = models.CharField(max_length=50, null=True)  # Фамилия
    middle_name = models.CharField(max_length=50, null=True)  # Отчество
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_of_birth = models.DateField(null=True, verbose_name="дата рождения")
    building = models.ForeignKey(Building, on_delete=models.SET_NULL, null=True)
    points = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to=f, null=True, blank=True)
    token = models.CharField(max_length=1000, null=True)
    peculiarity = models.CharField(max_length=1000, null=True, choices=PECULARITY_CHOICE, blank=True)
    two_auth = models.CharField(max_length=1000, null=True, blank=True, choices=TWO_AUTH_CHOICES)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', "second_name", "first_name", "middle_name"]

    objects = MyAccountManager()

    def __str__(self):
        return f"{self.second_name} {self.first_name} {self.middle_name}"

    def full_name(self):
        return f"{self.second_name} {self.first_name} {self.middle_name}"

    def has_classroom(self):
        if self.role == "teacher":
            if ClassRoom.objects.all().filter(teacher=self).exists():
                return True
        elif self.role == "student":
            if ClassRoom.objects.all().filter(member=self).exists():
                return True
        return False

    def get_classroom(self):
        if not self.has_classroom():
            return False
        if self.role == "teacher":
            return ClassRoom.objects.get(teacher=self)
        elif self.role == "student":
            return ClassRoom.objects.get(member=self)

    def get_events(self):
        events = EventsMembers.all().filter(user=self)
        return events

    def get_events_count(self):
        events = EventsMembers.all().filter(user=self)
        return len(events)

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def get_status(self):
        if self.points <= 200:
            return "Медный"
        elif self.points <= 400:
            return "Бронзовый"
        elif self.points <= 600:
            return "Серебряный"
        elif self.points <= 800:
            return "Золотой"
        else:
            return "Бриллиантовый"

    def has_module_perms(self, app_label):
        return True


    def get_avatar(self):
        #print("test")
        if self.avatar:
            return self.avatar.url
        else:
            text = self.first_name + " " + self.middle_name
            hash = 0
            color = ''
            for i in range(len(text)):
                hash = ord(text[i]) + ((hash << 5) - hash)
            for i in range(3):
                value = (hash >> (i * 8)) & 0xFF
                color += ('00' + hex(value)[2:])[-2:]
            bg = color

            r = int(bg[0:2], 16) / 255
            g = int(bg[2:4], 16) / 255
            b = int(bg[4:6], 16) / 255
            max_val = max(r, g, b)
            min_val = min(r, g, b)
            l = (max_val + min_val) / 2
            if max_val == min_val:
                h = s = 0
            else:
                d = max_val - min_val
                s = d / (2 - max_val - min_val) if l > 0.5 else d / (max_val + min_val)
                if max_val == r:
                    h = (g - b) / d + (6 if g < b else 0)
                elif max_val == g:
                    h = (b - r) / d + 2
                else:
                    h = (r - g) / d + 4
                h /= 6
            e = [h, s, l]
            if (e[0] < 0.55 and e[2] >= 0.5) or (e[0] >= 0.55 and e[2] >= 0.75):
                fc = '000000'  # черный
            else:
                fc = 'FFFFFF'  # белый

            avatar_url = f"https://ui-avatars.com/api/?name={self.first_name}+{self.middle_name}&background={bg}&color={fc}"
            return avatar_url


class Connections(models.Model):
    ip = models.CharField(max_length=50)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=1000, null=True)
    device_browser = models.CharField(max_length=1000, null=True, blank=True)
    device_system = models.CharField(max_length=1000, null=True, blank=True)
    last_activity = models.DateTimeField(null=True, auto_now_add=True)
    verify = models.BooleanField(default=False)

PersonalArea/views/admin.py
import uuid
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse, FileResponse
from django.shortcuts import render, redirect, get_object_or_404
from Accounts.models import Account
from MainApp.models import *
from django.utils.formats import localize

from PersonalArea.forms import *
from Accounts.forms import NewBuildingForm
from Accounts.models import Building
from Accounts import decorators
import io
import xlsxwriter
import pandas as pd
from PersonalArea.models import Notications, Message


@decorators.is_admin
def login_admin_user(request, user):
    if request.user.is_superuser:
        logout(request)
        user = get_object_or_404(Account, pk=user)
        login(request, user)
        return redirect("/lk/")


@decorators.is_admin
def user_create(request):
    if request.method == "GET":
        return redirect("/lk/users/list")
    else:
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=True)
        return redirect("/lk/users/list")
    return render(request, "adminpanel/user_create.html", {"form": form})

@decorators.is_admin
def user_delete(request, id):
    user = get_object_or_404(Account, pk=id)
    user.delete()
    return redirect("/lk/users/list")
@decorators.is_admin
def event_add_user(request, id, user):
    user = Account.objects.get(id=user)
    user = EventsMembers(user=user, is_active=False)
    user.save()
    event = Events.objects.get(pk=id)
    event.volunteer.add(user)
    return redirect(f"/lk/events/{id}/view")


@decorators.is_admin
def add_building(request):
    if request.method == "GET":
        form = NewBuildingForm()
    else:
        form = NewBuildingForm(request.POST)
        if form.is_valid():
            user = form.save(commit=True)
        return redirect("/lk/building/list")
    return render(request, "adminpanel/building_create.html", {"form": form, "section": "building"})


@decorators.is_admin
def building_list(request):
    context = {
        "buildings": Building.objects.all().order_by("-id"),
        "section": "building"
    }
    return render(request, "adminpanel/buildings_list.html", context=context)


@decorators.is_admin
def category_list(request):
    if request.method == "POST":
        form = EventCategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
    categories = EventCategory.objects.all()
    form = EventCategoryForm()
    return render(request, "adminpanel/category_list.html",
                  {"categories": categories, "form": form, "section": "events"})


@decorators.is_admin
def category_data(request, id):
    category = EventCategory.objects.get(pk=id)
    category_data = {
        'received': localize(datetime.now()),
        'category': {
            "id": category.id,
            "name": category.name,
            "methodists": {}
        }
    }
    for i in category.methodists.all():
        category_data['category']['methodists'][i.pk] = {
            "id": i.pk,
            "full_name": i.full_name(),

        }
    return JsonResponse(category_data, safe=False)


@decorators.is_admin
def category_edit(request, id):
    category = EventCategory.objects.get(pk=id)
    if request.method == "POST":
        form = EventCategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            form.save_m2m()
        return redirect("category_list")
    else:
        form = EventCategoryForm(instance=category)
        return render(request, "adminpanel/edit_category.html", {"section": "events", "form": form})

PersonalArea/templates/inc/admin_menu.html
<nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0"><a href="#" class="sidebar-toggler flex-shrink-0">
    <i class="fa fa-bars"></i>
</a>
    <div class="navbar-nav align-items-center ms-auto">
        <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                <img class="rounded-circle me-lg-2" id="user_avatar"
                     src="{{ user.get_avatar }}" alt=""
                     style="width: 40px; height: 40px;">
                <span class="d-none d-lg-inline-flex">{{ user.full_name }}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                <a href="/lk/settings/" class="dropdown-item">Настройки</a>
                <a href="/logout/" class="dropdown-item">Выйти</a>
            </div>
        </div>
    </div>
</nav>

<div id="has_avatar" style="display: none">{% if user.avatar %}yes{% else %}no{% endif %}</div>
{% block script %}
    <script>
        var stringToColor = function stringToColor(str) {
            var hash = 0;
            var color = '';
            var i;
            var value;
            var strLength;



            for (i = 0; i < str.length; i++) {
                hash = str.charCodeAt(i) + ((hash << 5) - hash);
            }

            for (i = 0; i < 3; i++) {
                value = (hash >> (i * 8)) & 0xFF;
                color += ('00' + value.toString(16)).substr(-2);
            }

            return color;
        };


        function rgb2hsl(HTMLcolor) {
            r = parseInt(HTMLcolor.substring(0, 2), 16) / 255;
            g = parseInt(HTMLcolor.substring(2, 4), 16) / 255;
            b = parseInt(HTMLcolor.substring(4, 6), 16) / 255;
            var max = Math.max(r, g, b), min = Math.min(r, g, b);
            var h, s, l = (max + min) / 2;
            if (max == min) {
                h = s = 0;
            } else {
                var d = max - min;
                s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
                switch (max) {
                    case r:
                        h = (g - b) / d + (g < b ? 6 : 0);
                        break;
                    case g:
                        h = (b - r) / d + 2;
                        break;
                    case b:
                        h = (r - g) / d + 4;
                        break;
                }
                h /= 6;
            }
            return [h, s, l]; // H - цветовой тон, S - насыщенность, L - светлота
        }

        function changeColor(HTMLcolor) {
            e = rgb2hsl(HTMLcolor);
            if ((e[0] < 0.55 && e[2] >= 0.5) || (e[0] >= 0.55 && e[2] >= 0.75)) {
                fc = '000000'; // черный
            } else {
                fc = 'FFFFFF'; // белый
            }
            return fc
            // далее меняем цвет, где это необходимо
        }

        function gen_avatar(fn, mn) {
            bg = stringToColor(fn+" "+mn)
            fc = changeColor(bg);

            avatar_url = `https://ui-avatars.com/api/?name=${fn}+${mn}&background=${bg}&color=${fc}`

            return avatar_url


        }
        has_avatar = document.querySelector("#has_avatar")
        avatar = document.querySelector("#user_avatar")
        //if (has_avatar.innerHTML === "no") {
        //    avatar.src = gen_avatar("{{ user.first_name }}", "{{ user.middle_name }}")

        //}
        //has_avatar.remove()
    </script>
{% endblock script %}

PersonalArea/templates/inc/footer.html
<div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Электронная книга волонтера</a>, все права защищены.
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                        </div>
                    </div>
                </div>
            </div>

PersonalArea/templates/inc/no_menu_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}Личный кабинет{% endblock title %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Загрузка...</span>
            </div>
        </div>
        <!-- Spinner End -->

        <!-- Content Start -->
        <div class="content open">
            {% block content %}

            {% endblock content %}
            <!-- Footer Start -->
            {% include 'inc/footer.html' %}
            <!-- Footer End -->
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

PersonalArea/templates/inc/sidebar_base.html
<div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-light navbar-light">
                <a href="index.html" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>Волонтер</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">{{ user.full_name }}</h6>
                        <span>{{ user.get_role_display }}</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    {% block sidebar %}
                    {% endblock sidebar %}
                </div>
            </nav>
        </div>