ChatBot/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path('', index),
]

PersonalArea/urls.py
from django.urls import path
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path("", views.other.index),
    path("chat/", views.other.chat),

    path("users/list/", views.administration.users_list),
    path("users/list/<str:role>", views.administration.users_list),
    path("users/create/", views.admin.user_create, name="create_user"),
    path("users/<int:id>/edit/", views.administration.edit_user),
    path("users/<int:id>/delete/", views.admin.user_delete),
    path("users/data/<int:id>", views.administration.user_data),
    path("users/<int:id>/view/", views.administration.view_user),
    path("users/<int:user>/login/", views.admin.login_admin_user),
    path("users/<int:user>/avatar/remove", views.administration.avatar_remove),
    path("events/<int:id>/view/", views.aam.events_view),
    path("events/category/list/", views.admin.category_list, name="category_list"),
    path("events/category/<int:id>/edit/", views.admin.category_edit),
    path("events/<int:id>/accept/<int:user>", views.aam.event_accept_user),
    path("events/<int:id>/reject/<int:user>", views.aam.event_reject_user),
    path("events/<int:id>/add/<int:user>", views.admin.event_add_user),
    path("events/<int:id>/export", views.aam.event_export),
    path("events/<int:id>/unarchived", views.aam.event_unarchived),
    path("events/<int:id>/archive", views.aam.event_archive),
    path("events/<int:id>/points/give", views.aam.give_points),
    path("events/<int:id>/photo/report", views.aam.photo_report),
    path("events/<int:id>/photo/report/<int:image>/delete", views.aam.photo_delete),
    path("events/<int:id>/detail", views.other.event_detail),
    path("events/category/data/<int:id>", views.admin.category_data),
    path("events/invites/", views.student.student_invites),
    path("events/all_events/", views.other.all_events),

    path("building/list/", views.admin.building_list),
    path("building/add/", views.admin.add_building),
    path("events/list/<str:search>", views.aam.events_list),
    path("events/archive/", views.aam.events_archive_list),
    path('settings/', views.other.edit_profile),
    path("events/create/", views.aam.event_create),

    path("classroom/create/", views.teacher.create_classroom),
    path("events/", views.other.events),
    path("events/<int:id>/invite", views.teacher.invite_classroom_event),

    path("classroom/invite/create/", views.teacher.create_invite),
    path("classroom/invite/update/", views.teacher.update_invite),
    path("classroom/invite/<uuid:classroom>/", views.student.invite),
    path("classroom/students/", views.teacher.classroom_students),

    path("classroom/student/<int:user>/view", views.teacher.classroom_view_student),
    path("classroom/student/<int:user>/export", views.other.classroom_view_export),

    path("events/<int:event>/request", views.student.event_request),
    path("my/events/", views.student.my_events),

    path("classrooms/", views.administration.classrooms_list, name="classrooms_list"),
    path("classrooms/<int:id>", views.administration.classrooms_view, name="classrooms_view"),
    path("settings/avatar/remove", views.other.avatar_remove, name="avatar_remove"),
    path('schedule/', views.psychologist.schedule_index, name="schedule_index"),
    path('schedule/add', views.psychologist.schedule_add, name="schedule_add"),

    path('schedule/<int:d>/<int:m>/<int:y>', views.psychologist.schedule_date, name="schedule_date"),
    path('schedule/calendar/', views.psychologist.calendar, name="calendar"),
    path('schedule/edit', views.psychologist.edit_schedule, name="edit_schedule"),
    path('schedule/has_month_classes/<int:m>/<int:y>', views.psychologist.has_month_classes, name="has_month_classes"),
    path('schedule/view/<int:id>', views.psychologist.view_schedule, name="view_schedule"),
    path('classes', views.psychologist.classes, name="classes"),
    path("settings/security/change-password/", views.other.change_password, name="change_password"),
    path("settings/security/devices/", views.other.devices, name="security"),
    path("settings/security/devices/delete/<str:device>", views.other.delete_device, name="delete_device"),
    path("settings/linking/mosru", views.other.settings_linking_mosru, name="settings_linking_mosru"),
# path("classroom/student/<int:user>/delete", views.classroom_delete_student),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

volunteer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from Accounts import views as accounts_views
from MainApp import views
from django.views.static import serve

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('register/<str:mode>/', accounts_views.register),
                  path('login/', accounts_views.login_request),
                  path('logout/', accounts_views.logout_request, name="logout"),

                  path('lk/', include("PersonalArea.urls")),
                  path('setup/', accounts_views.setup, name="setup"),
                  path('', views.index),
                  path('auth/', accounts_views.auth, name="auth"),
                  path('auth/mosru/', accounts_views.auth_mos_ru, name="auth"),
                  path('auth/mosru/info/', accounts_views.mos_ru_info, name="auth"),
                  path('auth/register', accounts_views.register_request),
                  path('auth/login', accounts_views.login_request),
                  path('chatbot/', include("ChatBot.urls")),
                  path("user_activity/", accounts_views.user_activity),
                  path("feedback/", views.feedback)
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


def handler404(request, *args, **argv):
    return render(request, 'errors/404.html', status=404)


def handler500(request, *args, **argv):
    return render(request, 'errors/500.html', status=500)


def handler403(request, *args, **argv):
    return render(request, 'errors/403.html', status=403)


handler403 = handler403
handler500 = handler500
handler404 = handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PersonalArea/models.py
import time

from django.db import models

from Accounts.models import Account


class Notications(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=1000)
    user = models.ForeignKey(Account, on_delete=models.CharField)
    created = models.IntegerField(blank=True,null=True)
    sent = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.created = round(time.time())
        super(Notications, self).save(*args, **kwargs)


class Message(models.Model):
    room = models.CharField(max_length=244)
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    context = models.TextField(max_length=3000)
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ('date_added',)

PersonalArea/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from Accounts.models import Account

from MainApp.models import Events, ClassRoom, EventCategory, PsychologistSchedule


class EditUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, disabled=True)

    class Meta:
        model = Account
        fields = (
            "username", "email", "second_name", "first_name", "middle_name", "date_of_birth", "building", "role",
            "points",'avatar', "peculiarity")
        labels = {
            "username": "Имя пользователя",
            "email": "Почта",
            "second_name": "Фамилия",
            "first_name": "Имя",
            "middle_name": "Отчество",
            "date_of_birth": "Дата рождения",
            "role": "Роль",
            "building": "Корпус",
            "points": "Баллов",
            "avatar": "Изображение",
            "peculiarity": "Особенность"
        }
        widgets = {
            'date_of_birth': forms.DateInput(
                format='%Y-%m-%d',
                attrs={'class': 'form-control',
                       'placeholder': 'Select a date',
                       'type': 'date'
                       }),
            'avatar': forms.FileInput(
                attrs={"class":"form-control"}
            )
        }

    def save(self, commit=True):
        user = super(EditUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class EditUserFormHeadTeacher(forms.ModelForm):
    class Meta:
        model = Account
        fields = ("peculiarity",)
        labels = {
            "peculiarity": "Особенность"
        }
        widgets = {
            'avatar': forms.FileInput(
                attrs={"class":"form-control"}
            )
        }

    def save(self, commit=True):
        user = super(EditUserFormHeadTeacher, self).save(commit=False)
        if commit:
            user.save()
        return user

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, label="Почта")

    class Meta:
        model = Account
        fields = (
            "username", "email", "second_name", "first_name", "middle_name", "password1", "password2", "date_of_birth",
            'building','role', "avatar")
        labels = {
            "username": "Имя пользователя",
            "email": "Почта",
            "second_name": "Фамилия",
            "first_name": "Имя",
            "middle_name": "Отчество",
            "date_of_birth": "Дата рождения",
            "building": "Корпус",
            'role': "Роль",
            'avatar': "Изображение"

        }
        widgets = {
            'date_of_birth': forms.DateInput(attrs={"type": "date"})
        }

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class EventAddForm(forms.ModelForm):
    class Meta:
        model = Events
        # Описываем поля, которые будем заполнять в форме
        fields = (
        'name', 'description', 'start_date', 'end_date', 'organizer', 'type','category', 'subject', 'classroom_number', 'building',
        'image')

        widgets = {
            'name': forms.TextInput(),
            'description': forms.Textarea(),
            'start_date': forms.DateTimeInput(format=['%d/%m/%y'], attrs={'type': 'datetime-local'}),
            'end_date': forms.DateTimeInput(format=['%d/%m/%y'], attrs={'type': 'datetime-local'}),
            'organizer': forms.Select(),
            'type': forms.Select(attrs={"onchange": "change(this)"}),
            'category': forms.Select(),
            'classroom_number': forms.Select(),
            'building': forms.Select(),
            'image': forms.FileInput(attrs={"class": "form-control"})
        }
        labels = {
            "name": "Название",
            "description": "Описание",
            "start_date": "Дата начала",
            "end_date": "Дата окончания",
            "organizer": "Организатор",
            "building": "Корпус",
            "classroom_number": "Доступно для",
            "image": "Изображение",
            "category": "Методическое объединение",
            "subject": "Предмет",
            "type": "Тип"
        }

    def save(self, commit=True):
        user = super(EventAddForm, self).save(commit=False)
        if commit:
            user.save()
        return user


class NewClassRoom(forms.ModelForm):
    class Meta:
        model = ClassRoom
        # Описываем поля, которые будем заполнять в форме
        fields = ('classroom', 'parallel')

        widgets = {
            'classroom': forms.NumberInput(),
            'parallel': forms.TextInput(attrs={"style": "text-transform:uppercase"}),
        }
        labels = {
            "classroom": "Класс",
            "parallel": "Паралель",
        }

    def unique(self):
        classroom = super(NewClassRoom, self).save(commit=False)
        if ClassRoom.objects.all().filter(classroom=classroom.classroom,
                                          parallel__iexact=str(classroom.parallel).upper()).exists():
            return False
        else:
            return True

    def save(self, commit=True):
        classroom = super(NewClassRoom, self).save(commit=False)
        classroom.parallel = str(classroom.parallel).upper()
        if commit:
            classroom.save()
        return classroom


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = (
            "username", "second_name", "first_name", "middle_name", "date_of_birth", "avatar")
        labels = {
            "username": "Имя пользователя",
            "second_name": "Фамилия",
            "first_name": "Имя",
            "middle_name": "Отчество",
            "date_of_birth": "Дата рождения",
            "avatar": "Изображение",
        }
        widgets = {
            'date_of_birth': forms.DateInput(
                format='%Y-%m-%d',
                attrs={'class': 'form-control',
                       'placeholder': 'Select a date',
                       'type': 'date'
                       }),
            'avatar': forms.FileInput(attrs={"class": "form-control"})
        }

    def save(self, commit=True):
        user = super(EditProfileForm, self).save(commit=False)
        if commit:
            user.save()
        return user


class EventCategoryForm(forms.ModelForm):
    class Meta:
        model = EventCategory
        # Описываем поля, которые будем заполнять в форме
        fields = ('name', 'methodists')
        labels = {
            "name": "Название",
            "methodists": "Методисты"
        }

    def save(self, commit=True):
        user = super(EventCategoryForm, self).save(commit=False)
        if commit:
            user.save()
        return user


class EventAddFormMethodist(forms.ModelForm):
    class Meta:
        model = Events
        # Описываем поля, которые будем заполнять в форме
        fields = ('name', 'description', 'start_date', 'end_date', 'category', 'classroom_number', 'building', 'image',
                  "organizer")

        widgets = {
            'name': forms.TextInput(),
            'description': forms.Textarea(),
            'start_date': forms.DateTimeInput(format=['%d/%m/%y'], attrs={'type': 'datetime-local'}),
            'end_date': forms.DateTimeInput(format=['%d/%m/%y'], attrs={'type': 'datetime-local'}),
            'building': forms.Select(),
            'image': forms.FileInput(attrs={"class": "form-control"})
        }
        labels = {
            "name": "Название",
            "description": "Описание",
            "start_date": "Дата начала",
            "end_date": "Дата окончания",
            "organizer": "Организатор",
            "building": "Корпус",
            "classroom_number": "Доступно для",
            "image": "Изображение",
            "category": "Категория"

        }

    def __init__(self, loggedin_user=None, *args, **kwargs):
        super(EventAddFormMethodist, self).__init__(*args, **kwargs)
        if loggedin_user is not None:
            self.fields['category'].queryset = EventCategory.objects.all().filter(methodists=loggedin_user)


    def save(self, commit=True):
        user = super(EventAddFormMethodist, self).save(commit=False)
        if commit:
            user.save()
        return user


class UploadPhotoReport(forms.Form):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'allow_multiple_selected': True, "class": "form-control", "accept": "image/*"}),
                           label="Изображения", )



class EventAddFormHeadTeacher(forms.ModelForm):
    class Meta:
        model = Events
        # Описываем поля, которые будем заполнять в форме
        fields = ('name', 'description', 'start_date', 'end_date', 'category', 'classroom_number', 'building', 'image',
                  "organizer")

        widgets = {
            'name': forms.TextInput(),
            'description': forms.Textarea(),
            'start_date': forms.DateTimeInput(format=['%d/%m/%y'], attrs={'type': 'datetime-local'}),
            'end_date': forms.DateTimeInput(format=['%d/%m/%y'], attrs={'type': 'datetime-local'}),
            'building': forms.Select(),
            'image': forms.FileInput(attrs={"class": "form-control"})
        }
        labels = {
            "name": "Название",
            "description": "Описание",
            "start_date": "Дата начала",
            "end_date": "Дата окончания",
            "organizer": "Организатор",
            "building": "Корпус",
            "classroom_number": "Доступно для",
            "image": "Изображение",
            "category": "Категория"

        }


    def __init__(self, loggedin_user=None, *args, **kwargs):
        super(EditUserFormHeadTeacher, self).__init__(*args, **kwargs)

PersonalArea/templates/aam/event_create.html
{% extends "inc/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-12 col-xl-12">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">Создание мероприятия</h6>
                    <form method="post" enctype="multipart/form-data">
                        <div class="mb-3">
                            {% csrf_token %}
                            {{ form|crispy }}
                        </div>
                        <button type="submit" class="btn btn-primary">Создать</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        const event_type = document.querySelector("#id_type")

        const subject_field = document.querySelector("#id_subject")
        const category_field = document.querySelector("#id_category")

        const div_subject_field = document.querySelector("#div_id_subject")
        const div_category_field = document.querySelector("#div_id_category")
        const change = (e) => {
            if (e.value === "subject") {
                div_subject_field.style.display = ""
                div_category_field.style.display = "none"
                category_field.getElementsByTagName("option")[0].selected=true
            } else {
                div_subject_field.style.display = "none"
                div_category_field.style.display = ""
                console.log(subject_field.getElementsByTagName("option"))
                subject_field.getElementsByTagName("option")[0].selected=true
            }
        }
        change(event_type)
    </script>
{% endblock content %}

PersonalArea/templates/aam/event_view.html
{% extends "inc/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">{{event.name}}</h6>
                <p>Описание: <strong>{{ event.description}}</strong></p>
                <p>Дата начала: <strong>{{ event.start_date}}</strong></p>
                <p>Дата окончания: <strong>{{ event.end_date}}</strong></p>
                <p>Организатор: <strong><a href="/lk/users/{{ event.organizer.pk}}/view">{{ event.organizer.full_name}}</a></strong></p>
                <p>Доступно для: <strong>{{ event.get_classroom_number_display}}</strong></p>
                <p>Корпус: <strong>{{ event.building.name}} ({{event.building.get_type_display}})</strong></p>
                {% if end %}
                <a href="/lk/events/{{event.pk}}/points/give" class="btn btn-primary">Выдать баллы</a>
                <a href="/lk/events/{{event.pk}}/photo/report" class="btn btn-primary">Фото отчет</a>
                {% endif %}
            </div>

        </div>
        <div class="{% if wait %}col-sm-12 col-xl-6{% else %}col-sm-12 col-xl-12{% endif %}">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Учасники</h6>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">ФИО</th>
                        {% if end %}
                        <th scope="col">Баллы</th>
                        {% endif %}
                    </tr>
                    </thead>
                    <tbody>
                    {% for member in members %}
                        <tr>
                            <td>{{ member.user.full_name }}</td>
                            {% if end %}
                                {%  if member.points %}
                                    <td>{{ member.points }}</td>
                                {% else %}
                                    <td>-</td>
                                {% endif %}
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% if wait %}
            <div class="col-sm-12 col-xl-6">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">Заявки</h6>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th scope="col">ФИО</th>
                            <th scope="col">Действия</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for member in reqs %}
                        <tr>
                            <td>{{member.user.full_name}}</td>
                            <td>
                                <a class="btn btn-success"  href="/lk/events/{{event.id}}/accept/{{member.pk}}"><i class="fa fa-check"></i></a>
                                <a class="btn btn-danger" href="/lk/events/{{event.id}}/reject/{{member.pk}}"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}
    </div>
</div>


{% endblock content %}

{% block js %}
    <script>
        console.log("{{ end }}")
    </script>
{% endblock js %}

PersonalArea/templates/aam/events_archive_list.html
{% extends "inc/base.html" %}
{% block content %}
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-6 col-xl-6">
                <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                    <i class="fa fa-calendar fa-3x text-primary"></i>
                    <div class="ms-3">
                        <p class="mb-2">Мероприятий</p>
                        <h6 class="mb-0">{{ count_events }}</h6>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xl-6">
                <div class="bg-light rounded d-flex align-items-center justify-content-between p-4">
                    <i class="fa fa-child fa-3x text-primary"></i>
                    <div class="ms-3">
                        <p class="mb-2">Заявок</p>
                        <h6 class="mb-0">{{ count_requests }}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Sales Chart Start -->
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-12 col-xl-12">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">Архив мероприятий
                    </h6>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th scope="col">Название</th>
                            <th scope="col">Дата начала</th>
                            <th scope="col">Дата конца</th>
                            <th scope="col">Действия</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for event in events %}
                            <tr>
                                <td><a href="/lk/events/{{ event.id }}/view">{{ event.name }}</a></td>
                                <td>{{ event.start_date }}</td>
                                <td>{{ event.end_date }}</td>
                                <td>
                                    <a class="btn btn-primary" href="/lk/events/{{ event.pk }}/unarchived"><i
                                            class="fas fa-box-open"></i></a>
                                    <a class="btn btn-primary" href="/lk/events/{{ event.pk }}/export"><i
                                            class="fas fa-file-download"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item {% if not events.has_previous %}disabled{% endif %}">
                                <a class="page-link"
                                   href="?page={% if events.has_previous %}{{ events.previous_page_number }}{% endif %}"
                                   tabindex="-1">&laquo;</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">{{ events.number }}</a></li>
                            <li class="page-item {% if not events.has_next %}disabled{% endif %}">
                                <a class="page-link" href="?page=
                                        {% if events.has_next %}{{ events.next_page_number }}{% endif %}">&raquo;</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- Sales Chart End -->


{% endblock content %}

PersonalArea/templates/aam/photo_report.html
{% extends "inc/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <style>
        .imgSelect {
             border: 5px solid #0d95e8;

        }
    </style>
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-12 col-xl-12">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">Фото отчет</h6>
                    <div class="row row-cols-1 row-cols-md-3 g-4">

                        {% for image in report %}
                            <div class="col">
                                <div class="card">
                                    <img src="{{ image.image.url }}" class="card-img-top" alt="image" width="100"
                                         height="300" style="">
                                    <div class="card-img-overlay" style="display: none">
                                        <input type="checkbox" class="form-check-input" style="width: 20px; height: 20px; opacity: .5; display: none">
                                        <a href="report/{{ image.pk }}/delete" class="btn btn-danger "
                                           style="opacity: .5"><i
                                                class="fa fa-trash"></i></a>
                                    </div>
                                </div>


                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid pt-4 px-4">
        <div class="row g-4">
            <div class="col-sm-12 col-xl-12">
                <div class="bg-light rounded h-100 p-4">
                    <h6 class="mb-4">Загрузка фото отчета</h6>
                    <form method="post" enctype="multipart/form-data">
                        <div class="mb-3">
                            {% csrf_token %}
                            {{ form|crispy }}
                        </div>
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">

                    <button type="button" class="btn-close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>

                    <img src="" class="imagepreview" style="width: 100%;">
                </div>
            </div>
        </div>
    </div>
    <script>
        console.log("test")
        const filee = document.querySelector("#id_file")
        console.log(filee)
        filee.setAttribute('multiple', '');

    </script>
    <script defer>
        let selected = 0
        const cards = document.querySelectorAll(".card")

        cards.forEach((item) => {
            let img = item.querySelector(".card-img-top")
            item.addEventListener("mouseover", () => {
                item.querySelector(".card-img-overlay").style.display = "block"
            })
            item.addEventListener("mouseout", () => {
                item.querySelector(".card-img-overlay").style.display = "none"
            })

            item.querySelector(".form-check-input").addEventListener("change", (e) => {
                let checked = e.target.checked
                if (checked) {
                    selected+=1
                    img.classList.add("imgSelect")
                } else {
                    selected-=1
                    img.classList.remove("imgSelect")
                }
            })
        })
    </script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script>


        $(function () {
            $('.pop').on('click', function () {
                $('.imagepreview').attr('src', $(this).find('img').attr('src'));
                $('#imagemodal').modal('show');
            });
        });
    </script>
{% endblock content %}